import world from "@/data/world-dots.json";
import { markets } from "@/data/site";
import { MarketsMap, type MapMarket } from "./MarketsMap";

/** Grid units → SVG units. */
const S = 6;

type WorldData = {
  cols: number;
  rows: number;
  dots: [number, number][];
  byCountry: Record<string, number[]>;
  centroids: Record<string, [number, number]>;
};

const data = world as unknown as WorldData;

// Manual label anchors (grid units) keep the tightly clustered Gulf markets legible.
const LABELS: Record<string, { x: number; y: number; anchor: "start" | "middle" | "end" }> = {
  lb: { x: 100, y: 17, anchor: "end" },
  kw: { x: 112.5, y: 13.5, anchor: "middle" },
  sa: { x: 103, y: 36, anchor: "end" },
  qa: { x: 120, y: 16, anchor: "start" },
  ae: { x: 123.5, y: 21.5, anchor: "start" },
  au: { x: 153.5, y: 59.5, anchor: "middle" },
  in: { x: 137, y: 36.5, anchor: "start" },
};

/**
 * Crop (grid units) of the full 180x69 dot field. Every market, the hub and
 * every label sit between x 85-160 and y 13-62; the Americas and the Atlantic
 * were half the old map's width and carried nothing. Cropping rather than
 * scaling means the hub renders large at every width, so no mobile zoom hack
 * is needed and there is nothing to scroll sideways.
 */
const VIEW = { x: 74, y: 9, w: 92, h: 52 };

/**
 * Server component: references the static base dot map and passes market
 * geometry plus India's own dots to the client overlay.
 */
export function WorldMap() {
  // Zero-length segments + round caps draw each dot in ~10 bytes of path data.
  const dotPath = (c: number, row: number) => `M${c * S + S / 2} ${row * S + S / 2}h0`;

  const toXY = ([c, row]: [number, number]) => ({ x: c * S + S / 2, y: row * S + S / 2 });

  const mapMarkets: MapMarket[] = markets.map((m) => {
    const l = LABELS[m.code];
    return {
      code: m.code,
      name: m.name,
      center: toXY(data.centroids[m.code]),
      label: { x: l.x * S, y: l.y * S, anchor: l.anchor },
    };
  });

  const hub = toXY(data.centroids.in);
  const hubLabel = { x: LABELS.in.x * S, y: LABELS.in.y * S, anchor: LABELS.in.anchor };
  const indiaPath = (data.byCountry.in ?? []).map((i) => dotPath(...data.dots[i])).join("");

  return (
    <MarketsMap
      viewBox={`${VIEW.x * S} ${VIEW.y * S} ${VIEW.w * S} ${VIEW.h * S}`}
      markets={mapMarkets}
      hub={hub}
      hubLabel={hubLabel}
      indiaPath={indiaPath}
    >
      {/* Base dot field is a static, cacheable asset (public/maps/world-dots.svg, generated by scripts/generate-world-dots.mjs). */}
      <image href="/maps/world-dots.svg" x="0" y="0" width={data.cols * S} height={data.rows * S} />
    </MarketsMap>
  );
}
